-- ════════════════════════════════════════════════════════════════════════════
-- production 컬럼 보정 — 승격(db push) **직전에 한 번** 실행합니다
-- ════════════════════════════════════════════════════════════════════════════
--
-- 실행 방법
--   Supabase 대시보드 → **production** 프로젝트 → SQL Editor → New query
--   → 이 파일 전체를 붙여넣고 Run.
--   ⚠ 첫 줄이 어느 프로젝트에 연결됐는지 출력합니다. **반드시 확인하고 실행하십시오.**
--
-- 왜 필요한가
--   production 에 있는 테이블 33개 중 **13개는 마이그레이션이 아니라 손으로 만들어졌습니다**
--   (`docs/admin/*_SETUP.sql` 계열). 그 13개를 만드는 마이그레이션은 아직 미적용이고,
--   전부 `create table if not exists` 로 시작합니다 — 즉 **이미 있는 테이블을 고치지 않습니다.**
--   그래서 손으로 만든 판에 없는 컬럼은 승격해도 생기지 않고, 바로 뒤따르는
--   인덱스·정책·트리거·함수가 그 컬럼을 참조하다 **그 지점에서 push 가 멈춥니다.**
--
--   실제로 그렇습니다: production 의 `content_items` 에는 `video_url` 이 없습니다.
--   그 마이그레이션은 다행히 `add column if not exists video_url` 을 갖고 있지만,
--   **나머지 151개 컬럼에는 그런 보정이 없습니다.**
--
-- 이 파일이 하는 일
--   13개 테이블의 **모든 선언 컬럼**에 `add column if not exists` 를 겁니다.
--   이미 있으면 아무 일도 하지 않습니다(no-op). 없으면 만듭니다. 데이터를 건드리지 않습니다.
--
-- 안전 장치
--   · `primary key`·`unique`·`references` 는 뗐습니다 — 이미 있는 테이블에 제약을 새로
--     거는 것은 잠금과 실패를 부릅니다. 컬럼만 맞춥니다.
--   · default 가 없는 `not null` 은 뗐습니다 — 행이 하나라도 있으면 실패하기 때문입니다.
--     default 가 있는 것은 그대로 둡니다(Postgres 가 채워 넣습니다).
--   · 따라서 이 파일은 **되돌릴 일이 없습니다.** 컬럼이 늘 뿐 줄지 않습니다.
--
-- ⚠ 실행 후 확인
--   맨 아래 검증 질의가 **여전히 없는 컬럼**을 찍습니다. 비어 있어야 다음 단계로 갑니다.
--   비어 있지 않다면 그 테이블은 이름만 같고 모양이 다른 것이므로 사람이 판단해야 합니다.
-- ════════════════════════════════════════════════════════════════════════════

select current_database() as db,
       current_setting('request.jwt.claim.iss', true) as issuer,
       inet_server_addr()::text as host,
       '⚠ 이 결과가 production 인지 확인하고 아래를 실행하십시오' as check_first;


-- ── ad_tracking_events (7개) ──────────────────────────────────────────────
alter table public.ad_tracking_events
  add column if not exists id bigint generated always as identity,
  add column if not exists event_type text check (event_type in ('ad_click','birth_info_completed','signup','first_consultation')),
  add column if not exists tracking_code text,
  add column if not exists ad_id uuid,
  add column if not exists user_id uuid,
  add column if not exists visitor_id text,
  add column if not exists created_at timestamptz not null default now();

-- ── admin_users (4개) ──────────────────────────────────────────────
alter table public.admin_users
  add column if not exists user_id uuid,
  add column if not exists role text not null default 'admin',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists created_by uuid;

-- ── advertisements (14개) ──────────────────────────────────────────────
alter table public.advertisements
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists public_tracking_code text,
  add column if not exists ad_type text not null default 'other' check (ad_type in ('youtube_shorts','youtube_video','instagram_reels','instagram_post','other')),
  add column if not exists publisher_nickname text,
  add column if not exists ad_check_url text,
  add column if not exists start_date date,
  add column if not exists contract_type text not null default 'other' check (contract_type in ('experience_group','self_produced','review_agency','direct_contract','other')),
  add column if not exists cost_krw bigint check (cost_krw is null or cost_krw >= 0),
  add column if not exists notes text,
  add column if not exists status text not null default 'draft' check (status in ('draft','active','ended','disabled')),
  add column if not exists schema_version text not null default 'ads@1.0.0',
  add column if not exists published_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- ── ai_usage_logs (4개) ──────────────────────────────────────────────
alter table public.ai_usage_logs
  add column if not exists id bigint generated by default as identity,
  add column if not exists request_type text not null default 'chat',
  add column if not exists status text,
  add column if not exists created_at timestamptz not null default now();

-- ── content_assets (20개) ──────────────────────────────────────────────
alter table public.content_assets
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists content_id uuid,
  add column if not exists kind text,
  add column if not exists status text not null default 'pending',
  add column if not exists provider text,
  add column if not exists provider_job_id text,
  add column if not exists prompt text,
  add column if not exists model text,
  add column if not exists aspect_ratio text,
  add column if not exists duration_seconds int,
  add column if not exists width int,
  add column if not exists height int,
  add column if not exists storage_path text,
  add column if not exists external_url text,
  add column if not exists error_code text,
  add column if not exists last_error text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_by uuid default auth.uid(),
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- ── content_items (12개) ──────────────────────────────────────────────
alter table public.content_items
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists title text not null default '',
  add column if not exists channel text not null default 'generic',
  add column if not exists source_type text not null default 'operator',
  add column if not exists famous_id uuid,
  add column if not exists status text not null default 'draft',
  add column if not exists body text,
  add column if not exists summary text,
  add column if not exists tags jsonb not null default '[]'::jsonb,
  add column if not exists created_by uuid default auth.uid(),
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- ── content_publications (17개) ──────────────────────────────────────────────
alter table public.content_publications
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists content_id uuid,
  add column if not exists channel text,
  add column if not exists status text not null default 'draft',
  add column if not exists scheduled_at timestamptz,
  add column if not exists timezone text,
  add column if not exists published_at timestamptz,
  add column if not exists external_id text,
  add column if not exists external_url text,
  add column if not exists attempt_count int not null default 0,
  add column if not exists last_error text,
  add column if not exists provider text,
  add column if not exists idempotency_key text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_by uuid default auth.uid(),
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- ── content_versions (14개) ──────────────────────────────────────────────
alter table public.content_versions
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists content_id uuid,
  add column if not exists version int not null default 1,
  add column if not exists title text,
  add column if not exists body text,
  add column if not exists summary text,
  add column if not exists source text not null default 'manual',
  add column if not exists provider text,
  add column if not exists model text,
  add column if not exists prompt_version text,
  add column if not exists input_ref jsonb,
  add column if not exists token_usage jsonb,
  add column if not exists created_by uuid default auth.uid(),
  add column if not exists created_at timestamptz not null default now();

-- ── famous_ai_suggestions (9개) ──────────────────────────────────────────────
alter table public.famous_ai_suggestions
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists famous_id uuid,
  add column if not exists suggestion jsonb,
  add column if not exists provider text,
  add column if not exists model text,
  add column if not exists workload text,
  add column if not exists prompt_version text,
  add column if not exists created_by uuid default auth.uid(),
  add column if not exists created_at timestamptz not null default now();

-- ── famous_profiles (22개) ──────────────────────────────────────────────
alter table public.famous_profiles
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists slug text,
  add column if not exists name text,
  add column if not exists category text,
  add column if not exists occupation text,
  add column if not exists short_description text,
  add column if not exists bio text,
  add column if not exists birth_info jsonb,
  add column if not exists birth_source text not null default 'unknown',
  add column if not exists birth_source_note text,
  add column if not exists status text not null default 'draft',
  add column if not exists is_public boolean not null default false,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists canonical_url text,
  add column if not exists index_policy text not null default 'noindex',
  add column if not exists calculation_state text not null default 'not_calculated',
  add column if not exists current_snapshot_id uuid,
  add column if not exists created_by uuid default auth.uid(),
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists published_at timestamptz;

-- ── famous_snapshots (8개) ──────────────────────────────────────────────
alter table public.famous_snapshots
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists famous_id uuid,
  add column if not exists birth_fingerprint text,
  add column if not exists engine_version text,
  add column if not exists rule_set_version text,
  add column if not exists result jsonb,
  add column if not exists created_by uuid default auth.uid(),
  add column if not exists created_at timestamptz not null default now();

-- ── provider_connections (8개) ──────────────────────────────────────────────
alter table public.provider_connections
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists channel text,
  add column if not exists status text not null default 'not_connected',
  add column if not exists external_account_id text,
  add column if not exists external_account_name text,
  add column if not exists connected_at timestamptz,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

-- ── user_acquisition_attribution (12개) ──────────────────────────────────────────────
alter table public.user_acquisition_attribution
  add column if not exists user_id uuid,
  add column if not exists first_ad_id uuid,
  add column if not exists first_tracking_code text,
  add column if not exists first_visitor_id text,
  add column if not exists first_touch_at timestamptz,
  add column if not exists latest_ad_id uuid,
  add column if not exists latest_touch_at timestamptz,
  add column if not exists signup_at timestamptz,
  add column if not exists first_consultation_at timestamptz,
  add column if not exists schema_version text not null default 'ads@1.0.0',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();


-- ════════════════════════════════════════════════════════════════════════════
-- 검증 — 여기가 **비어 있어야** 승격으로 넘어갑니다
-- ════════════════════════════════════════════════════════════════════════════
with expected(tbl, col) as (values
  ('ad_tracking_events','id'),
  ('ad_tracking_events','event_type'),
  ('ad_tracking_events','tracking_code'),
  ('ad_tracking_events','ad_id'),
  ('ad_tracking_events','user_id'),
  ('ad_tracking_events','visitor_id'),
  ('ad_tracking_events','created_at'),
  ('admin_users','user_id'),
  ('admin_users','role'),
  ('admin_users','created_at'),
  ('admin_users','created_by'),
  ('advertisements','id'),
  ('advertisements','public_tracking_code'),
  ('advertisements','ad_type'),
  ('advertisements','publisher_nickname'),
  ('advertisements','ad_check_url'),
  ('advertisements','start_date'),
  ('advertisements','contract_type'),
  ('advertisements','cost_krw'),
  ('advertisements','notes'),
  ('advertisements','status'),
  ('advertisements','schema_version'),
  ('advertisements','published_at'),
  ('advertisements','created_at'),
  ('advertisements','updated_at'),
  ('ai_usage_logs','id'),
  ('ai_usage_logs','request_type'),
  ('ai_usage_logs','status'),
  ('ai_usage_logs','created_at'),
  ('content_assets','id'),
  ('content_assets','content_id'),
  ('content_assets','kind'),
  ('content_assets','status'),
  ('content_assets','provider'),
  ('content_assets','provider_job_id'),
  ('content_assets','prompt'),
  ('content_assets','model'),
  ('content_assets','aspect_ratio'),
  ('content_assets','duration_seconds'),
  ('content_assets','width'),
  ('content_assets','height'),
  ('content_assets','storage_path'),
  ('content_assets','external_url'),
  ('content_assets','error_code'),
  ('content_assets','last_error'),
  ('content_assets','metadata'),
  ('content_assets','created_by'),
  ('content_assets','created_at'),
  ('content_assets','updated_at'),
  ('content_items','id'),
  ('content_items','title'),
  ('content_items','channel'),
  ('content_items','source_type'),
  ('content_items','famous_id'),
  ('content_items','status'),
  ('content_items','body'),
  ('content_items','summary'),
  ('content_items','tags'),
  ('content_items','created_by'),
  ('content_items','created_at'),
  ('content_items','updated_at'),
  ('content_publications','id'),
  ('content_publications','content_id'),
  ('content_publications','channel'),
  ('content_publications','status'),
  ('content_publications','scheduled_at'),
  ('content_publications','timezone'),
  ('content_publications','published_at'),
  ('content_publications','external_id'),
  ('content_publications','external_url'),
  ('content_publications','attempt_count'),
  ('content_publications','last_error'),
  ('content_publications','provider'),
  ('content_publications','idempotency_key'),
  ('content_publications','metadata'),
  ('content_publications','created_by'),
  ('content_publications','created_at'),
  ('content_publications','updated_at'),
  ('content_versions','id'),
  ('content_versions','content_id'),
  ('content_versions','version'),
  ('content_versions','title'),
  ('content_versions','body'),
  ('content_versions','summary'),
  ('content_versions','source'),
  ('content_versions','provider'),
  ('content_versions','model'),
  ('content_versions','prompt_version'),
  ('content_versions','input_ref'),
  ('content_versions','token_usage'),
  ('content_versions','created_by'),
  ('content_versions','created_at'),
  ('famous_ai_suggestions','id'),
  ('famous_ai_suggestions','famous_id'),
  ('famous_ai_suggestions','suggestion'),
  ('famous_ai_suggestions','provider'),
  ('famous_ai_suggestions','model'),
  ('famous_ai_suggestions','workload'),
  ('famous_ai_suggestions','prompt_version'),
  ('famous_ai_suggestions','created_by'),
  ('famous_ai_suggestions','created_at'),
  ('famous_profiles','id'),
  ('famous_profiles','slug'),
  ('famous_profiles','name'),
  ('famous_profiles','category'),
  ('famous_profiles','occupation'),
  ('famous_profiles','short_description'),
  ('famous_profiles','bio'),
  ('famous_profiles','birth_info'),
  ('famous_profiles','birth_source'),
  ('famous_profiles','birth_source_note'),
  ('famous_profiles','status'),
  ('famous_profiles','is_public'),
  ('famous_profiles','seo_title'),
  ('famous_profiles','seo_description'),
  ('famous_profiles','canonical_url'),
  ('famous_profiles','index_policy'),
  ('famous_profiles','calculation_state'),
  ('famous_profiles','current_snapshot_id'),
  ('famous_profiles','created_by'),
  ('famous_profiles','created_at'),
  ('famous_profiles','updated_at'),
  ('famous_profiles','published_at'),
  ('famous_snapshots','id'),
  ('famous_snapshots','famous_id'),
  ('famous_snapshots','birth_fingerprint'),
  ('famous_snapshots','engine_version'),
  ('famous_snapshots','rule_set_version'),
  ('famous_snapshots','result'),
  ('famous_snapshots','created_by'),
  ('famous_snapshots','created_at'),
  ('provider_connections','id'),
  ('provider_connections','channel'),
  ('provider_connections','status'),
  ('provider_connections','external_account_id'),
  ('provider_connections','external_account_name'),
  ('provider_connections','connected_at'),
  ('provider_connections','metadata'),
  ('provider_connections','updated_at'),
  ('user_acquisition_attribution','user_id'),
  ('user_acquisition_attribution','first_ad_id'),
  ('user_acquisition_attribution','first_tracking_code'),
  ('user_acquisition_attribution','first_visitor_id'),
  ('user_acquisition_attribution','first_touch_at'),
  ('user_acquisition_attribution','latest_ad_id'),
  ('user_acquisition_attribution','latest_touch_at'),
  ('user_acquisition_attribution','signup_at'),
  ('user_acquisition_attribution','first_consultation_at'),
  ('user_acquisition_attribution','schema_version'),
  ('user_acquisition_attribution','created_at'),
  ('user_acquisition_attribution','updated_at')
)
select e.tbl, e.col, '⚠ 아직 없습니다' as state
from expected e
where not exists (
  select 1 from information_schema.columns c
  where c.table_schema = 'public' and c.table_name = e.tbl and c.column_name = e.col
)
order by e.tbl, e.col;
