-- ============================================================================
-- DeokbunAI — ai_usage_logs: schema of record + the missing `request_id` column
--
-- OWNER_APPLY_REQUIRED — DO NOT auto-apply. Additive + idempotent + non-destructive.
-- No existing row is read, written, moved or deleted. No column is dropped or retyped.
--
-- WHY THIS EXISTS
--   `public.ai_usage_logs` was created OUTSIDE this migration set, so the repo had no
--   definition for it at all — only the additive telemetry migration
--   (20260818000000) that assumes it. That gap caused a real, silent production defect:
--
--     • `request_id` does not exist on staging (verified 2026-09-02: PostgREST 42703).
--     • `logAiUsage()` retries three ways — (1) row + request_id + telemetry `extra`,
--       (2) row + request_id, (3) the bare row. Steps 1 and 2 BOTH carry request_id, so
--       both fail, and step 3 carries NO telemetry `extra`.
--     • Result: `cached_input_tokens`, `reasoning_tokens`, `max_output_tokens`,
--       `complexity`, `reasoning_effort` have been NULL on every row ever written.
--       Measured on the 2026-09-02 cost benchmark: 72/72 successful calls, all NULL.
--
--   One missing column has been disabling the entire cost-breakdown feature that
--   Commercial Quality Sprint §13 shipped. Adding it restores three things at once:
--   token↔call joins, prompt-cache hit rate, and the reasoning share of output cost.
--
-- WHAT THIS DOES
--   1. Records the table's real shape as a `create table if not exists`. On any
--      environment where the table already exists this is a NO-OP — it exists so a
--      fresh environment gets the same table, and so the repo stops being silent about it.
--   2. Adds every column with `add column if not exists`, so an environment that is
--      missing one converges without touching the ones it has.
--   3. Adds `request_id` + a partial index.
--
-- LIMITATION — READ BEFORE RELYING ON §1
--   The column list and types below were read from the LIVE staging PostgREST schema
--   (2026-09-02), which exposes names, types, nullability and defaults but NOT RLS
--   policies, grants, triggers or check constraints. If the real table carries any of
--   those, they are NOT reproduced here and a fresh environment built from this file
--   alone would differ. Treat §1 as documentation of the columns, not as a full
--   provisioning script, until the original DDL is recovered or RLS is re-declared.
-- ============================================================================

-- ── 1. schema of record (no-op where the table already exists) ──────────────────────────
create table if not exists public.ai_usage_logs (
  id                  bigint generated by default as identity primary key,
  user_id             uuid,
  conversation_id     uuid,
  model               text,
  request_type        text        not null default 'chat',
  input_tokens        integer,
  output_tokens       integer,
  total_tokens        integer,
  latency_ms          integer,
  status              text        not null,
  error_code          text,
  created_at          timestamptz not null default now(),
  -- Cost telemetry (added by 20260818000000; repeated here so the full shape is in one place).
  cached_input_tokens integer,
  reasoning_tokens    integer,
  max_output_tokens   integer,
  complexity          text,
  reasoning_effort    text
);

-- ── 2. converge any environment that is missing a column ────────────────────────────────
alter table public.ai_usage_logs
  add column if not exists user_id             uuid,
  add column if not exists conversation_id     uuid,
  add column if not exists model               text,
  add column if not exists input_tokens        integer,
  add column if not exists output_tokens       integer,
  add column if not exists total_tokens        integer,
  add column if not exists latency_ms          integer,
  add column if not exists error_code          text,
  add column if not exists cached_input_tokens integer,
  add column if not exists reasoning_tokens    integer,
  add column if not exists max_output_tokens   integer,
  add column if not exists complexity          text,
  add column if not exists reasoning_effort    text;

-- ── 3. the missing column ───────────────────────────────────────────────────────────────
-- `text`, not `uuid`: the Edge currently sends crypto.randomUUID() strings, but request_id is a
-- correlation label rather than a key, and a non-UUID caller must not make the insert fail —
-- failing is precisely how the telemetry was lost in the first place. Nullable: rows written
-- before this migration keep their NULL and are still valid usage rows.
alter table public.ai_usage_logs
  add column if not exists request_id text;

-- Partial index: only non-null values are ever looked up, and most historical rows are NULL.
create index if not exists ai_usage_logs_request_id_idx
  on public.ai_usage_logs (request_id)
  where request_id is not null;

-- Time-window lookups are the fallback join path while old rows have no request_id.
create index if not exists ai_usage_logs_created_at_idx
  on public.ai_usage_logs (created_at desc);
